# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. `make.jl` reads `pages` from this file; the API
# reference pages (lib/public.md, lib/internals.md) and the README-derived home
# page are generated by `make.jl`.

pages = [
    "Home" => "index.md",
    # Authored quickstart + infrastructure guide (package-owned source pages,
    # distinct from the README-derived home page).
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Infrastructure and template sync" => "getting-started/infrastructure.md",
        "Customising your docs" => "getting-started/customising.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ]
]
