# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. `make.jl` reads `pages` from this file; the API
# reference pages (lib/public.md, lib/internals.md) and the README-derived home
# page are generated by `make.jl`.

pages = [
    "Home" => "index.md",
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ]
]
