name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    uses: EpiAware/.github/.github/workflows/coverage.yml@1b36d466be7e132c3a8a4f75d9ac90d9642c6f81
    with:
      julia_version: '1'
    secrets: inherit  # pragma: allowlist secret
