name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    uses: EpiAware/.github/.github/workflows/coverage.yml@dc919e0d1674c16d1518df07eda5ee0be09b47e2
    with:
      julia_version: '1'
    secrets: inherit  # pragma: allowlist secret
