name: Documenter

on:
  push:
    branches: main
    tags: '*'
  pull_request:
  merge_group:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Documenter:
    uses: EpiAware/.github/.github/workflows/documentation.yml@1b36d466be7e132c3a8a4f75d9ac90d9642c6f81
    secrets: inherit  # pragma: allowlist secret
