name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    uses: EpiAware/.github/.github/workflows/format-check.yml@1b36d466be7e132c3a8a4f75d9ac90d9642c6f81
    secrets: inherit  # pragma: allowlist secret
