name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  pre-commit:
    uses: EpiAware/.github/.github/workflows/format-check.yml@6d4e35e2515f947acbf7d2a683cbf02b341005c7
    secrets: inherit  # pragma: allowlist secret
