name: TagBot

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: "3"

jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    uses: EpiAware/.github/.github/workflows/tagbot.yml@0b92629d0e7663ba8708af5b4d2f8e03d05fea2c
    with:
      lookback: ${{ github.event.inputs.lookback || '3' }}
    secrets: inherit  # pragma: allowlist secret
