name: Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: EpiAware/.github/.github/workflows/tests.yml@6d4e35e2515f947acbf7d2a683cbf02b341005c7
    secrets: inherit  # pragma: allowlist secret

  downgrade-compat:
    uses: EpiAware/.github/.github/workflows/downgrade.yml@6d4e35e2515f947acbf7d2a683cbf02b341005c7
    secrets: inherit  # pragma: allowlist secret
